= Cloud Native Application Architectures with Spring and Cloud Foundry

== Goals



== Instructor Details



== Schedule

This is _loose_ schedule for the two days. We will adjust as necessary based on our pace through the material.

The lectures for this class are intentionally very light and are only intended to set the stage for the hands-on labs.
The overwhelming majority of our time will be spent engaging with the technology directly!

NOTE: We will be updating the course materials throughout the class. You will need to have the materials cloned and track the master branch.

This can be accomplished as follows:

----
$ git clone https://github.com/Pivotal-Field-Engineering/cloud-workshop
----

Fork workspace repo https://github.com/Pivotal-Field-Engineering/cloud-workspace and clone

----
$ git clone https://github.com/<username>/cloud-workspace
----

=== Day One

9:00 AM - 12:00 AM:: *Session 1:* _Building Twelve-Factor Apps with Spring Boot_
12:00 PM - 13:00 PM:: Lunch
13:00 PM - 1:30 AM:: *Session 2:* _Cloud-Native Architecture Overview_
1:30 PM - 2:00 PM:: Afternoon Break
2:00 PM - 6:00 PM:: *Session 3:* _Connecting the dots with Spring Cloud Services_

=== Day Two

9:00 AM - 12:00 AM:: *Session 4:* _Securing Cloud-Native Applications_
12:00 AM - 1:00 PM:: Lunch
1:00 PM - 4:00 PM:: *Session 5:* _Deliver Mobile Capability with Pivotal Mobile Services_
4:00 PM - 4:30 PM:: Afternoon Break
4:30 PM - 5:00 PM:: Review

== Course Materials

=== Day One
1. Building Twelve-Factor Apps with Spring Boot
    - Getting Started with _Spring Boot, Initialiser, CLI_
    - Deploying a Web Application with an _Embedded Container_
    - Externalizing Configuration with Spring Boot
    - Introspection, Monitoring, and Metrics using Spring Boot Actuator
    - Build a Hypermedia-Driven RESTful Web Service with Spring Data REST
2. Cloud-Native Architecture Overview
    - Operating Twelve-Factor Apps with Cloud Foundry
    - From Zero to Pushing Your First Application
    - Binding to Cloud Foundry Services
3. Connecting the dots with Spring Cloud Services
    - Deploying and Using Spring Cloud Config Server to manage external configuration
    - Using Service Discovery for loosely coupled distributed systems
    - Building and monitoring resilient distributed systems with Circuit Breaker

=== Day Two
4. Securing Cloud-Native Applications
    - Intro to OAuth2 and Open ID Connect
    - Using the UAA to secure internal applications (where users are developers)
    - Using Pivotal SSO to secure end user applications (where users are within or outside of the organization)
    - Securing app to app communication with the multi-tenancy features of UAA
5. Deliver Mobile Capability with Pivotal Mobile Services
    - Keep users engaged with Push Notification Service
    - Aggregate and transform legacy backends for mobile consumption with API Gateway
    - Use Data Sync for seamless multi-device user experiences
    - Release mobile apps to internal users early and often with App Distribution
