:compat-mode:
= Lab 4 - From Zero to Pushing Your First Application

== Target

. If you haven't already, download the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Set the API target for the CLI:
+
----
$ cf api apj.fe.pivotal.io --skip-ssl-validation
----

. Login to Pivotal Web Services:
+
----
$ cf login
----
+
Follow the prompts.

== Build and Push!

. Change to the _Hello_ sample application directory:
+
----
$ cd $COURSE_HOME/hello-spring-boot
----

. Using the Gradle, build and package the application:
+
----
$ ./gradlew assemble
----
+
The Gradle Wrapper will automatically download the appropriate version of Gradle for this project along with all of _Hello Spring Boot_'s dependencies. This may take a few moments.

. Push the application!
+
----
$ cf push hello --random-route -p build/libs/hello-0.0.1-SNAPSHOT.jar
----
+
You should see output similar to the following listing. Take a look at the listing callouts for a play-by-play of what's happening:
+
====
----
Creating app hello in org APJ / space test as admin...
OK <1>

Creating route hello-crumbliest-street.apj.fe.pivotal.io...
OK <2>

Binding hello-crumbliest-street.apj.fe.pivotal.io to hello...
OK <3>

Uploading hello... <4>
Uploading app files from: build/libs/hello-0.0.1-SNAPSHOT.jar
Uploading 527.4K, 87 files
Done uploading
OK


Starting app hello in org APJ / space test as admin... <5>
-----> Downloaded app package (11M)
-----> Java Buildpack Version: v2.7.1 (offline) | https://github.com/cloudfoundry/java-buildpack#fee275a
-----> Downloading Open Jdk JRE 1.8.0_40 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_40.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (0.9s)  <6>
-----> Downloading Spring Auto Reconfiguration 1.7.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.7.0_RELEASE.jar (found in cache)

-----> Uploading droplet (50M) <7>

1 of 1 instances running

App started


OK

App hello was started using this command `SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.7.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx768M -Xms768M -XX:MaxMetaspaceSize=104857K -XX:MetaspaceSize=104857K -Xss1M org.springframework.boot.loader.JarLauncher`<8>

Showing health and status for app hello in org APJ / space test as admin...
OK <9>

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: hello-crumbliest-street.apj.fe.pivotal.io
last uploaded: Tue Jul 7 06:30:47 UTC 2015
stack: cflinuxfs2
buildpack: java-buildpack=v2.7.1-offline-https://github.com/cloudfoundry/java-buildpack#fee275a java-main open-jdk-jre=1.8.0_40 spring-auto-reconfiguration=1.7.0_RELEASE

     state     since                    cpu    memory         disk           details
#0   running   2015-07-07 02:31:26 PM   0.0%   429.4M of 1G   113.5M of 1G

----
<1> In most cases, the CLI indicates each Cloud Foundry API call as it happens.
In this case, the CLI has created an application record for _Spring Music_ in your assigned space.
<2> All HTTP/HTTPS requests to applications will flow through Cloud Foundry's front-end router called http://docs.cloudfoundry.org/concepts/architecture/router.html[(Go)Router].
Here the CLI is creating a route with random word tokens inserted (again, see `manifest.yml` for a hint!) to prevent route collisions across the default `cfapps.io` domain.
<3> Now the CLI is _binding_ the created route to the application.
Routes can actually be bound to multiple applications to support techniques such as http://www.mattstine.com/2013/07/10/blue-green-deployments-on-cloudfoundry[blue-green deployments].
<4> The CLI finally uploads the application bits to PWS. Notice that it's uploading _90 files_! This is because Cloud Foundry actually explodes a ZIP artifact before uploading it for caching purposes.
<5> Now we begin the staging process. The https://github.com/cloudfoundry/java-buildpack[Java Buildpack] is responsible for assembling the runtime components necessary to run the application.
<6> Here we see the version of the JRE that has been chosen and installed.
<7> The complete package of your application and all of its necessary runtime components is called a _droplet_.
Here the droplet is being uploaded to PWS's internal blobstore so that it can be easily copied to one or more _http://docs.cloudfoundry.org/concepts/architecture/execution-agent.html[Droplet Execution Agents (DEA's)]_ for execution.
<8> The CLI tells you exactly what command and argument set was used to start your application.
<9> Finally the CLI reports the current status of your application's health.
You can get the same output at any time by typing `cf app spring-music`.
====

. Visit the application in your browser by hitting the route that was generated by the CLI:
