= Lab 3 - Introspection, Monitoring, and Metrics using Spring Boot Actuator

== Introspection Endpoints

. Run the application:
+
----
$ java -jar build/libs/hello-0.0.1-SNAPSHOT.jar
----

. Try out the following endpoints. The output is omitted here because it can be quite large:
+
http://localhost:8080/beans:: Dumps all of the beans in the Spring context.
http://localhost:8080/autoconfig:: Dumps all of the auto-configuration performed as part of application bootstrapping.
http://localhost:8080/configprops:: Displays a collated list of all `@ConfigurationProperties`.
http://localhost:8080/env:: Dumps the application's shell environment as well as all Java system properties.
http://localhost:8080/mappings:: Dumps all URI request mappings and the controller methods to which they are mapped.
http://localhost:8080/dump:: Performs a thread dump.
http://localhost:8080/trace:: Displays trace information (by default the last few HTTP requests).

== Health Indicators

Spring Boot provides an endpoint (http://localhost:8080/health) that allows for the notion of various health indicators.

. Normally, when Spring Security is not enabled, the `/health` endpoint will only expose an `UP` or `DOWN` value.
To simplify working with the endpoint for this lab, we will turn off its sensitivity.
Add the following to `src/main/resources/application.yml`:
+
----
endpoints:
  health:
    sensitive: false
----

. Create the class `io.pivotal.spring.hello.FlappingHealthIndicator` and into it paste the following code:
+
----
@Component
public class FlappingHealthIndicator implements HealthIndicator{

    private Random random = new Random(System.currentTimeMillis());

    @Override
    public Health health() {
        int result = random.nextInt(100);
        if (result < 50) {
            return Health.down().withDetail("flapper", "failure").withDetail("random", result).build();
        } else {
            return Health.up().withDetail("flapper", "ok").withDetail("random", result).build();
        }
    }
}
----
+
This demo health indicator will randomize the health check.

. Build the application:
+
----
$ gradle build
----

. Run the application:
+
----
$ java -jar build/libs/hello-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080/health), and verify that the output is similar to the following (and changes randomly!):
+
----
{
  status: "UP",
  flapping: {
    status: "UP",
    flapper: "ok",
    random: 69
  },
  diskSpace: {
    status: "UP",
    free: 113632186368,
    threshold: 10485760
  }
}
----

== Metrics

Spring Boot provides an endpoint (http://localhost:8080/metrics) that exposes several automatically collected metrics for your application.
It also allows for the creation of custom metrics.

. Create the class `io.pivotal.spring.hello.GreetingService` and into it paste the following code:
+
----
@Component
public class GreetingService {

    @Autowired
    CounterService counterService;

    @Value("${greeting}")
    String greeting;

    public String getGreeting() {
        counterService.increment("counter.services.greeting.invoked");
        return greeting;
    }
}
----
+
This class is using the `@Autowired` `CounterService` to count the number of times that the `getGreeting()` method has been invoked.

. Refactor the contents of the class `io.spring.hello.Application`:
+
----
@Autowired
private GreetingService greetingService;

@RequestMapping("/")
public String hello() {
    return String.format("%s World!", greetingService.getGreeting());
}

----
+
`hello()` is now delegating the source of the greeting to our newly created `GreetingService`.

. Build the application:
+
----
$ gradle build
----

. Run the application:
+
----
$ java -jar build/libs/hello-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080) and refresh the page several times.

. Now visit the `/metrics` endpoint (http://localhost:8080/metrics).
Among the autogenerated metrics you should see a `counter` for the `GreetingService` invocations:
+
----
counter.services.greeting.invoked: 16,
----
+
To learn more about the autogenerated metrics, visit http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html.

link:lab_04.adoc[From Zero to Pushing Your First Application]